---
title: "Informe Canarias desigualdades sociales en salud"
subtitle: "Proyecto FIS XX"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(ggplot2)
```

## Diabetes {.tabset}

``` {r, echo=F}

ejemplo_datos <- read_xlsx("ejemplo_datos.xlsx")
datos_canarias <- ejemplo_datos %>%
  filter(nombre == "Canarias")

```

### Global

``` {r, echo=F}

datos_canarias %>%
  filter(fr =="diabetes", sexo=="Overall") %>%
  ggplot(aes(x=encuesta, y=Varlor)) +
  geom_point() +
  geom_linerange(aes(ymin=infci, ymax=supci))

```

### Hombres

``` {r, echo=F}

datos_canarias %>%
  filter(fr =="diabetes", sexo=="Men") %>%
  ggplot(aes(x=encuesta, y=Varlor)) +
  geom_point() +
  geom_linerange(aes(ymin=infci, ymax=supci))

```

### Mujeres

``` {r, echo=F}

datos_canarias %>%
  filter(fr =="diabetes", sexo=="Women") %>%
  ggplot(aes(x=encuesta, y=Varlor)) +
  geom_point() +
  geom_linerange(aes(ymin=infci, ymax=supci))

```


## Hipertensión arterial {.tabset}

### Global

``` {r, echo=F}

datos_canarias %>%
  filter(fr =="hta", sexo=="Overall") %>%
  ggplot(aes(x=encuesta, y=Varlor)) +
  geom_point() +
  geom_linerange(aes(ymin=infci, ymax=supci))

```

### Hombres

``` {r, echo=F}

datos_canarias %>%
  filter(fr =="hta", sexo=="Men") %>%
  ggplot(aes(x=encuesta, y=Varlor)) +
  geom_point() +
  geom_linerange(aes(ymin=infci, ymax=supci))

```

### Mujeres

``` {r, echo=F}

datos_canarias %>%
  filter(fr =="hta", sexo=="Women") %>%
  ggplot(aes(x=encuesta, y=Varlor)) +
  geom_point() +
  geom_linerange(aes(ymin=infci, ymax=supci))

```


